### ISSUE TITLE
Problems with UIHostingView?

### ISSUE THREAD

**Issue by hng001** [nelglez/stripe-swiftui#1]
When I clicked pay button, I encountered this bug:

2020-05-03 21:09:17.093651+0800 Stripe-SwiftUI[40570:800201] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000021fa7b0 h=--& v=--& _UIToolbarContentView:0x7fcb5fe59c60.height == 0   (active)>",
    "<NSLayoutConstraint:0x6000021a1cc0 V:|-(0)-[_UIButtonBarStackView:0x7fcb5fe47440]   (active, names: '|':_UIToolbarContentView:0x7fcb5fe59c60 )>",
    "<NSLayoutConstraint:0x6000021a2ee0 _UIButtonBarStackView:0x7fcb5fe47440.bottom == _UIToolbarContentView:0x7fcb5fe59c60.bottom   (active)>",
    "<NSLayoutConstraint:0x6000021fb4d0 UIButtonLabel:0x7fcb5fd627b0'Next'.centerY == _UIModernBarButton:0x7fcb5fc4c780'Next'.centerY + 0.5   (active)>",
    "<NSLayoutConstraint:0x6000021fb160 'TB_Baseline_Baseline' _UIModernBarButton:0x7fcb5fc4c780'Next'.lastBaseline == UILayoutGuide:0x600003bd3100'UIViewLayoutMarginsGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x6000021fb1b0 'TB_Top_Top' V:|-(>=0)-[_UIModernBarButton:0x7fcb5fc4c780'Next']   (active, names: '|':_UIButtonBarButton:0x7fcb5fc4c5b0 )>",
    "<NSLayoutConstraint:0x6000021fb520 'UIButtonBar.maximumAlignmentSize' _UIButtonBarButton:0x7fcb5fc4c5b0.height == UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide'.height   (active)>",
    "<NSLayoutConstraint:0x6000021a1270 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':_UIButtonBarStackView:0x7fcb5fe47440 )>",
    "<NSLayoutConstraint:0x6000021fab20 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600003bd3100'UIViewLayoutMarginsGuide']-(16)-|   (active, names: '|':_UIButtonBarButton:0x7fcb5fc4c5b0 )>",
    "<NSLayoutConstraint:0x6000021a1450 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide']   (active, names: '|':_UIButtonBarStackView:0x7fcb5fe47440 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000021fb4d0 UIButtonLabel:0x7fcb5fd627b0'Next'.centerY == _UIModernBarButton:0x7fcb5fc4c780'Next'.centerY + 0.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-05-03 21:09:17.095135+0800 Stripe-SwiftUI[40570:800201] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000021f93b0 h=--& v=--& _UIToolbarContentView:0x7fcb5fe59c60.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000021a13b0 H:|-(0)-[_UIButtonBarStackView:0x7fcb5fe47440]   (active, names: '|':_UIToolbarContentView:0x7fcb5fe59c60 )>",
    "<NSLayoutConstraint:0x6000021a0fa0 H:[_UIButtonBarStackView:0x7fcb5fe47440]-(0)-|   (active, names: '|':_UIToolbarContentView:0x7fcb5fe59c60 )>",
    "<NSLayoutConstraint:0x6000021fad50 'TB_Leading_Leading' H:|-(20)-[_UIModernBarButton:0x7fcb5fc4c780'Next']   (active, names: '|':_UIButtonBarButton:0x7fcb5fc4c5b0 )>",
    "<NSLayoutConstraint:0x6000021faf30 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fcb5fc4c780'Next']-(20)-|   (active, names: '|':_UIButtonBarButton:0x7fcb5fc4c5b0 )>",
    "<NSLayoutConstraint:0x6000021fa5d0 'UISV-canvas-connection' UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide'.leading == UIView:0x7fcb5fc4c440.leading   (active)>",
    "<NSLayoutConstraint:0x6000021fa1c0 'UISV-canvas-connection' UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7fcb5fc4c5b0.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021fad00 'UISV-spacing' H:[UIView:0x7fcb5fc4c440]-(0)-[_UIButtonBarButton:0x7fcb5fc4c5b0]   (active)>",
    "<NSLayoutConstraint:0x6000021a1310 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7fcb5fe47440 )>",
    "<NSLayoutConstraint:0x6000021a3930 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600003b448c0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7fcb5fe47440 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000021faf30 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fcb5fc4c780'Next']-(20)-|   (active, names: '|':_UIButtonBarButton:0x7fcb5fc4c5b0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

Any idea what's going here in this bug?

**Comment by nelglez** [comment]
I dont see this problem on my app.
