### ISSUE TITLE
unable to integrate my https://aidanstripe.herokuapp.com backend

### ISSUE THREAD

**Issue by aidan305** [nelglez/stripe-swiftui#3]
Hi,
I am trying to modify your code to integrate it with the example mobile backend by stripe found here: https://github.com/stripe/example-mobile-backend/tree/v17.0.0 I updated the endpoints and base url in MyAPIClient and changed the requests but when I run the app and click continue the console just prints server error. 
would you be able to offer some help with my integration?

thanks,
Aidan

**Comment by nelglez** [comment]
You will need to look at your console, server logs, and stripe logs for a better understanding of what is happening.
