### ISSUE TITLE
Clicking "cancel" on payment options view does not dismiss the view

### ISSUE THREAD

**Issue by btian** [nelglez/stripe-swiftui#4]
Do you have the same problem?

**Comment by nelglez** [comment]
@btian Nope. I can click cancel and the view dismissed properly.

**Comment by btian** [comment]
Hmm I feel like I'm taking crazy pills. If I remove `if self.paymentContextDelegate.paymentMethodButtonTitle != "Select Payment Method" {` statement, then everything seems to work.

But if not, then I seem to get frozen at payment options screen.

It's so weird.
